### ISSUE TITLE
how to login or register?

### ISSUE THREAD

**Issue by SahilJaiswal24** [Saketh-Chandra/Hostel_Room_Booking#13]
please share login id and password or which email id is accessible, to access the website?

**Comment by Saketh-Chandra** [comment]
Yeah, sure!
For the [master branch](https://github.com/Saketh-Chandra/Hostel_Management_System/tree/master)!

- Admin Username: **saketh**
- Admin Password: **saketh**
- And the valid Email address should be like 
   - ABCD@bl.students.amrita.edu for Student
   - ABCD@bl.warden.amrita.edu for the warden
   - for the chief warden Admin should change the warder group to chief warden group
